[[main]]
none = "none"

[[main]]
name = "Posts"
pre = "fire"
pageRef = "/posts"
identifier = "1nmBwS51QB"
weight = 1

#[[main]]
#name = "Oracle"
#pageRef = "/PrivacyPolicy"
#weight = 2

#[[main]]
#name = "RAC"
#parent = "Oracle"
#pageRef = "/PrivacyPolicy"
#weight = 2

[[main]]
name = "Privacy Policy"
pageRef = "/PrivacyPolicy"
weight = 3

[[footer]]
none = "none"
